name: Sync with Canvas

on: push

jobs:
  sync:
    name: Sync with Canvas

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install byebug
        run: gem install byebug # hidden dep, could remove this if source code for github-to-canvas is updated

      - name: Install github-to-canvas
        run: gem install github-to-canvas

      - name: Sync with canvas
        run: github-to-canvas -a -lr --forkable
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
          CANVAS_API_PATH: ${{ secrets.CANVAS_API_PATH }}
