name: Sync with Canvas

on: push

jobs:
  sync:
    name: Sync with Canvas

    runs-on: ubuntu-latest

    steps:
      env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install byebug
        run: gem install byebug # hidden dep, could remove this if source code for github-to-canvas is updated
      - name: Install github-to-canvas
        run: gem install github-to-canvas
      - name: Sync with canvas
        run: github-to-canvas --align-from-github https://github.com/learn-co-curriculum/react-hooks-jest-testing --course 3264 --id 68021 --type assignment -lr --forkable --contains-html
        
