name: Sync with Canvas

on: push

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: gem install github-to-canvas
      - name: Sync with canvas
        run: github-to-canvas --align-from-github https://github.com/learn-co-curriculum/react-hooks-dq-conditional-rendering --course 3264 --id 6593 --type discussion -lr --forkable --contains-html
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
